application: applicationname
version: 1
runtime: python
api_version: 1

handlers:
- url: /images/
  static_dir: images
- url: /js/
  static_dir: js
- url: /css/
  static_dir: css
- url: /search
  script: search.py
- url: /suggest
  script: search.py
- url: /.*
  script: search.py
